# ------ASTEROIDS-----------------
ASTEROID_MIN_RADIUS = 20
ASTEROID_KINDS = 4
ASTEROID_SPAWN_RATE_SECONDS = 0.8
ASTEROID_MAX_RADIUS = ASTEROID_MIN_RADIUS * ASTEROID_KINDS
ASTEROID_SPLIT_ACCELERATION = 2.1
MIN_ASTEROID_SPLIT_FACTOR = 0.3
HEALTH_BAR_HEIGHT = 10

# -----COLORS----------------------
BLACK = (0, 0, 0)
BLUE = (0, 0, 255)
CYAN = (0, 255, 255)
GRAY = (128, 128, 128)
GREEN = (0, 255, 0)
MAGENTA = (255, 0, 255)
RED = (255, 0, 0)
WHITE = (255, 255, 255)
YELLOW = (255, 255, 0)

# -----DRONES-----------------------
DRONE_ORBIT_ANGLE_OFFSET = 0
DRONE_ORBIT_RADIUS = 55
DRONE_ORBIT_SPEED = 120
DRONE_RADIUS = 14
DRONE_SHOT_SPEED = 600
DRONE_SHOOT_COOLDOWN_SECONDS = 0.4
DRONE_TURN_SPEED = 450

# -----MENUS / GAME STATES-----------
GAME_OVER = "game_over"
GAME_RUNNING = "game_running"
PAUSED = "paused"
MAIN_MENU = "main_menu"

# -----PLAYER-----------------------
PLAYER_ACCELERATION_RATE = 125
PLAYER_BLINK_TIMER = 0.2
PLAYER_BRAKE_SPEED = 350
PLAYER_DECELERATION_RATE = 15
PLAYER_RADIUS = 20
PLAYER_RESPAWN_COOLDOWN_SECONDS = 3
PLAYER_SPEED = 200
PLAYER_STRAFE_SPEED = 225
PLAYER_TOP_SPEED = 450
PLAYER_TURN_SPEED = 300
LIFE_LOSS_SCORE = -50
GAME_OVER_SCORE = -500

# -----SCREEN-----------------------
LINE_WIDTH = 2
MENU_BUTTON_HEIGHT = 10
SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720
SCREEN_TOP = 0
SCREEN_BOTTOM  = SCREEN_HEIGHT
SCREEN_LEFT = 0
SCREEN_RIGHT = SCREEN_WIDTH

# -----SHOT-------------------------
BASE_SCORE = 50
SHOT_DAMAGE = 1
SHOT_RADIUS = 4

